### PR TITLE
update dependencies and add xml2js parser config

### PR DESCRIPTION
**Pull request by bettysteger**
use explicitArray:false as parser config -> to get object not array.

I think all single nodes should be objects not arrays!

### CODE REVIEW

**Comment by AnSavvides** [comment]
Thanks for the pull request, yup what you are suggesting makes sense.

It looks like Travis [isn't happy](https://travis-ci.org/AnSavvides/tvrage-json/builds/52187227) - it fails for Node.js v0.8, I suspect one of the updated dependencies doesn't support v0.8.

If you've got time and could look into that, that would be awesome - then I'll be happy to merge once Travis is happy again :)

**Comment by lpsBetty** [comment]
Hmm, I tried, I am really new to node.js, so I have no idea what to do here!

Is it possible to drop node.js 8.0 support? :D .. just asking.. or I downgrade some dependencies again.

**Comment by lpsBetty** [comment]
Somehow now it says 

````
Error: no test specified
The command "npm test" exited with 0.
````
do you know why?

**Comment by AnSavvides** [comment]
@lpsBetty sorry this took me a little while to get to - cool, it looks like Travis is happy again :) Thank you for your contribution!

**Comment by bettysteger** [comment]
@AnSavvides  oh nooooo, it just **looks like** that travis is happy!
see this log: https://travis-ci.org/AnSavvides/tvrage-json/jobs/55651583

sorry for the inconvenience, but I don't know why something had changed?
and why the build is passing, when there an error..

**Comment by AnSavvides** [comment]
As far as I can see, it all looks ok! I just tried a clean `npm install tvragejson` and everything seems fine, so no need to panic :)

**Pull request merged**
